### ISSUE TITLE
Fabric: EpisodeFragment onCompletion IllegalStateException when fragment is hidden

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#109]
#### in org.kpcc.android.EpisodeFragment$6.onCompletion

* Number of crashes: 48
* Impacted devices: 43

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56b1d382f5d3a7f76b8b88d0](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56b1d382f5d3a7f76b8b88d0)

**Comment by bricker** [comment]
Fixed in next release
