### ISSUE TITLE
Fabric: ConnectivityManager fails to start when streamManager isn't loaded (NPE)

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#111]
#### in org.kpcc.android.LiveFragment$1.onConnect

* Number of crashes: 49
* Impacted devices: 40

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56bd8a07f5d3a7f76bc40df6](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56bd8a07f5d3a7f76bc40df6)

**Comment by bricker** [comment]
Fixed in next release
