### ISSUE TITLE
Storage/retrieval of user's preferred stream (via DataManager)

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#129]
When the user has successfully validated their pledge token, they will be allowed to pick which stream to listen to (normal or pledge-free). This should be stored via DataManager for some amount of time so the user doesn't have to insert their token every time.

@sdillingham @vsinghkpcc How long should this preference be stored until the user must re-authenticate? Does it depend on the "pledgeType" value? (once, monthly)

**Comment by bricker** [comment]
This will live in XFSManager

**Comment by sdillingham** [comment]
The token should live for the duration of the drive and expire when the drive ends.
