### ISSUE TITLE
NPE on LiveFragment onClick

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#132]
#### in org.kpcc.android.LiveFragment$6.onClick

* Number of crashes: 49
* Impacted devices: 47

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56c69ed1f5d3a7f76bf01b95](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56c69ed1f5d3a7f76bf01b95)

**Comment by bricker** [comment]
This should be fixed in the refactor release
