### ISSUE TITLE
NPE LiveFragment.onClick

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#141]
#### in org.kpcc.android.LiveFragment$7.onClick

* Number of crashes: 49
* Impacted devices: 41

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56c6359bf5d3a7f76bee3907](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56c6359bf5d3a7f76bee3907)

**Comment by bricker** [comment]
Duplicate, closing.
