### ISSUE TITLE
NPE in Episode json builder

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#142]
#### in org.kpcc.api.Episode.buildFromJson

* Number of crashes: 49
* Impacted devices: 17

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/575cabb0ffcdc042502bd31f](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/575cabb0ffcdc042502bd31f)

**Comment by bricker** [comment]
This seems to be related to some schedule change, as it just started happening a few days ago
