### ISSUE TITLE
OutOfMemory error in getTimeFormat

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#154]
#### in org.kpcc.android.StreamManager.getTimeFormat
- Number of crashes: 46
- Impacted devices: 36

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56d017d3f5d3a7f76b1e874a](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/56d017d3f5d3a7f76b1e874a)

**Comment by bricker** [comment]
Closing this as it hasn't occurred in 30+ days
