### ISSUE TITLE
OutOfMemory error Segment.java line 62

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#167]
#### in com.android.okhttp.okio.Segment.

* Number of crashes: 48
* Impacted devices: 30

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/57407e65ffcdc042502e2c22](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/57407e65ffcdc042502e2c22)

**Comment by bricker** [comment]
Closing this as it hasn't occurred in 30+ days
