### ISSUE TITLE
ArrayList.java line 310

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#172]
#### in java.util.ArrayList.get

* Number of crashes: 45
* Impacted devices: 39

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/570588c3ffcdc042507c4384](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/570588c3ffcdc042507c4384)

**Comment by bricker** [comment]
This is an error in Exoplayer — this will be fixed with the upcoming Exoplayer update work.

**Comment by bricker** [comment]
Closing as duplicate
