### ISSUE TITLE
Cannot dismiss notification on app launch

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-Android#175]
BUG: The KPCC notification is not dismissable unless you turn your phone on and off or uninstall the app.

**Comment by bricker** [comment]
From Jason:
The notification for the app (is that the right term--the banner that is visible when I swipe down from the top of my screen) is handy for switching back to the app from other things. Problem: When I get to work, I'd like to close the app. But I can't get that notification to go away no matter what I try. For example, I can right-swipe the app from my recent apps view. For every other app I use, that shuts it down. But not the KPCC app. Ultimately I can "force close" the app to kill the notification but that is cumbersome. Suggestion: all my other audio apps (Spotify, podcast player etc) use the notification for helpful audio control, and include an "x" or swipe functionality to close them with one touch
