### ISSUE TITLE
XFS Manager error

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#176]
#### in org.kpcc.android.XFSManager$1.done

* Number of crashes: 48
* Impacted devices: 19

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/588d551f0aeb16625ba50634](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/588d551f0aeb16625ba50634)

**Comment by bricker** [comment]
Fixed
