### ISSUE TITLE
ArrayList.java line 413

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-Android#177]
#### in java.util.ArrayList.get

* Number of crashes: 48
* Impacted devices: 33

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/58457cfa0aeb16625ba3c052](https://fabric.io/scpr/android/apps/com.skyblue.pra.kpcc/issues/58457cfa0aeb16625ba3c052)

**Comment by bricker** [comment]
Same error as #172
