### ISSUE TITLE
Back button behavior

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#18]
Maybe the back button should always (eventually) lead back to the Live Stream page. So the only place to exit the app with the back button is from the Live page ("home" page).

**Comment by sdillingham** [comment]
+1 to this. Both myself and a KPCC staffer who is an Android user found the back button functionality awkward in terms of where it took you. I would add to this, though, and say that the back button should always lead back to the player UI for whatever is currently playing - either the live stream or an episode. When we designed the app, a key concept was that all roads lead back to the player.

**Comment by bricker** [comment]
Cool, got it.

**Comment by bricker** [comment]
I updated the behavior here to be better, it's not exactly like the iOS app but I don't want to fight Android's navigation architecture too much. So now it behaves like a normal back button, where pretty much anything you do will be added onto the stack and the back button will just pop them off in order.
