### ISSUE TITLE
Write Test Specs For Playing Livestream

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/KPCC-Android#182]
This is for @jeffc-kpcc 

Write out the test cases for QA that should cover the flow from a user opening an app to a user playing the livestream and verifying that the stream is playable.  The test cases should be pretty granular and avoid using technical jargon as well as KPCC jargon.

I'd imagine something like this but with more specifics about how to trigger reach test case.

1. Open the app. Is there a loading image?
2. Look at the app. Is there a play button in the middle of the screen?
3. Click on the play button. Is there sound coming out?
4. Listen to the sound for 5 minutes. Does the sound continue without repeating/looping.

Feel free to just add the test cases as a comment here.

AC:
- [ ] there is a list of test cases to reproduce a user opening the app and listening to the livestream

**Comment by jeffc-kpcc** [comment]
1. Launch the KPCC Android app. 
2. Press the circular play button in the center of the screen. 
3. The app may - or may not - display an image (with the label “A KPCC UNDERWRITER MESSAGE” beneath it) and play a short audio clip of approximately 15-30 seconds in length. 
    1. Question: *If* the underwriter message image appears, does the audio clip play through until its completion? 
    2. Question: *If* the underwriter message image appears, does it go away automatically once the audio clip completes? 
4. Once the underwriter message goes away - or if it was never displayed - live audio content should begin playing. 
    1. Question: Does the live audio play automatically? 
    2. Question: Did the live audio skip, stall, or otherwise fail if played for at least 5 minutes? 
5. While the audio is playing and at least a minute has passed, tap the left-most ’30’ button. 
    1. Question: Does the audio rewind by 30 seconds and continue playing? 
6. After rewinding at least 30 seconds, tap the right-most '30' button. 
    1. Question: Does the audio fast-forward by 30 seconds and continue playing? 
7. While the audio is playing and at least two minutes have passed, slide the audio scrubbing control as far as you can to the left. 
    1. Question: Does the audio begin playing again? 
    2. Question: Is there a label (located approximately in the center of the screen) that says “15 MINUTES BEFORE LIVE” or similar? 
8. While the audio is playing and after rewinding using the audio scrubbing control, slide the audio scrubbing control as far as you can to the right. 
    1. Question: Does the audio begin playing again? 
    2. Question: Is there a label (located approximately in the center of the screen) that says “LIVE”? 
9. While the audio is playing and after rewinding using the audio scrubbing control, tap the “Rewind to the start of this show” button at the bottom of the screen. 
    1. Question: Does the audio begin playing again? 
    2. Question: Did the audio scrubbing control progress bar move all the way to the left side of the loading progress indicator? 
10. While the audio is playing, tap the “Back to Live” button. 
    1. Question: Does the audio begin playing again? 
    2. Question: Did the audio scrubbing control progress bar move all the way to the right side of the loading progress indicator? 
11. Press the circular pause button in the center of the screen. 
    1. Question: Does the audio stop/pause?

**Comment by jeffc-kpcc** [comment]
A simplified and revised version of the above.

1. Launch the KPCC Android app. 
2. Press the circular play button in the center of the screen. 
3. The app may - or may not - play a short 15 to 30 minute audio clip. 
    1. Question: *If* the audio plays, does it play through until completion? 
    2. Question: *If* the audio plays, does an image with the words “A KPCC UNDERWRITER MESSAGE” appear on the top half of the screen? 
    3. Question: *If* the image and words “A KPCC UNDERWRITER MESSAGE” appeared, do they go away once the audio clip finishes playing? 
4. Live audio content should begin playing. 
    1. Question: Does the live audio play automatically? 
    2. Question: Did the live audio skip, repeat, stall, or otherwise fail when played for at least 5 minutes? 
5. While the audio is playing and at least a minute has passed, tap the left-most ’30’ button. 
    1. Question: Does the audio rewind by 30 seconds and continue playing? 
6. Tap the right-most '30' button. 
    1. Question: Does the audio fast-forward by 30 seconds and continue playing? 
7. Tap the “Rewind to the start of this show” button at the bottom of the screen. 
    1. Question: Does the audio begin playing again? 
8. While the audio is playing, tap the “Back to Live” button. 
    1. Question: Does the audio begin playing again? 
9. Press the circular pause button in the center of the screen. 
    1. Question: Does the audio stop/pause?

**Comment by nakedsushi** [comment]
👍 :shipit:
