### ISSUE TITLE
Certain On-Demand Programs produce "Stream Error"

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-Android#186]
The following programs produce a "stream error" when trying to play an episode:
- The California Report
- The Dinner Party Download
- KPCC News
- Marketplace
- Marketplace Weekend
- This American Life
- The World

(special cases)
- Off-ramp (program page itself doesn't load)
- BBC Newshour (the last march 30 ep "Revolt Against..." doesn't load)

NOTE: In the iOS app, most of these seem to take a longer time to load than normal - though they do eventually load

**Comment by bricker** [comment]
This is happening because the URLs for these audio streams are HTTP code 302 (redirect) and Exoplayer was ignore those. I've fixed it in 113.
