### ISSUE TITLE
Error screen needs better design

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#20]
Error screen is kinda basic, could use some love:

![screenshot_2015-03-28-18-13-12](https://cloud.githubusercontent.com/assets/978899/6883689/61901fe4-d576-11e4-9ccf-2261df31db36.png)

**Comment by sdillingham** [comment]
I think we keep this simple. The error message is good; I would just vertically center it, make the font about 50% bigger, put some extra left and right padding on either side, and call this issue closed.

**Comment by bricker** [comment]
Got it!
