### ISSUE TITLE
"Skipped On Demand" event

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#21]
@sdillingham The analytics document shows an event for "skipped episodes". I don't see it implemented in the iOS app — what's the threshold for whether an episode was "skipped" or not?

For now I have it send an event if someone swipes away before listening to 1/4 of the episode. I can also set it to a static 10 seconds or whatever. Let me know, thanks!

**Comment by sdillingham** [comment]
Thanks Bryan, we may have missed that event in the rush to get 3.0.0 out the door. I like the notion of a skip being when a user has listened to less then 25% of the episode. Let's go with that.

**Comment by bricker** [comment]
Cool, thanks!
