### ISSUE TITLE
Episode Seek touch area is too small

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#41]
Episode seek is difficult because the seek area is so small.

@sdillingham I took out the default blue "dot" for seeking because it was ugly. If you want to send me something better I can drop it in there.

**Comment by sdillingham** [comment]
Is it possible to natively draw a round dot at the playhead whose diameter is about 6-8 times the height of the progress bar (see attached screenshot). It would mean that the episode "elapsed / duration" label above the progress bar would need to be bumped up a bit to leave room for the dot.
![segment player - program episode](https://cloud.githubusercontent.com/assets/442483/6999913/4bf5e5c2-dbcc-11e4-94b5-fed81e937a9f.png)

**Comment by bricker** [comment]
Yep I can do that — I thought a static image might be better to keep the amount of drawing low, but I think it's simple enough that it won't add any UI lag.
