### ISSUE TITLE
Need placeholder (generated) avatars

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#44]
Some program avatars are missing and they're getting cached images instead on the programs list.

**Comment by sdillingham** [comment]
I think your note in this issue about the avatars being "generated" captures the requirement here, but just to confirm that in the iPhone app we dynamically create a generic avatar with the first letter of the show's name when we don't have an image.

**Comment by bricker** [comment]
Yep, I will add this in for the next release.

**Comment by bricker** [comment]
Hey @sdillingham this is done now, but I noticed while working on it that the set of icons for the Android app and iPhone app are different — I'm missing some that are present in the iOS app, and the iOS app is missing Q (which I have).

If you want to fix this discrepancy go ahead and send me the missing avatars:

* Invisibilia
* Marketplace Morning Report
* Take Two Evenings
* The World

I'm also missing Filmweek Marquee and Take Two Evenings but I've just duplicated the avatars for Filmweek and Take Two respectively.

Thanks!

**Comment by bricker** [comment]
Oops — I actually have most of those, I think they're just named incorrect for the dynamic lookup.

Invisibilia is missing still, I guess because it's new.

**Comment by bricker** [comment]
Also I see that the iPhone app has a hardcoded list of hidden programs (Filmweek Marquee and Take Two Evenings) — I guess you want this in the Android app too? I'll add it unless you say otherwise.

**Comment by sdillingham** [comment]
Good catch Bryan - yes, please exclude those two programs from the Android app. I'll attach the Invisibilia avatars to the other issue you filed and assigned to me
