### ISSUE TITLE
Need to refine text sizing logic for `episode_title` in Episode player

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#49]
Somewhat related to the Live Stream text sizing issue (#43), it would be nice to dynamically scale the type for episode titles down so that they fit onto 2 lines, maybe three at most. iOS has a `sizeToFit` utility that handles this for us in the iPhone app; not sure if Android has something similar.

**Comment by bricker** [comment]
Android has no such thing :( I'll add the same logic from the Live player (which needs to be fixed first).
