### ISSUE TITLE
Audio stops playing when exiting out of the app via hardware back button

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#50]
Right now if you back out of the app entirely using the hardware back button, all audio playback stops. I'm interested to know if this was an intentional choice. I checked a couple other popular audio apps (Pandora, Spotify) and it seems like the convention is to continue playback in the background.

**Comment by bricker** [comment]
This was intentional, to match the Android convention that the back button from a root screen "quits" the app (plus it's the default behavior) — I agree that it's a little confusing though. I'll find out how to work around it.
