### ISSUE TITLE
Headlines progress indicator sticks around a long time if Short List is slow to load

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#51]
When the progress indicator overlays on top of the Short List as it first loads, I think it's set to disappear once the webpage has finished loading. On cellular connections, that can take a while, resulting in the progress loader floating on top of the UI as a user starts to scroll. I only see `onPageStarted` and   `onPageFinished` methods in the Android docs; if it's not possible to remove the indicator once the webiew has started to render and draw the page, maybe we should just remove the spinner? Or maybe `onPageStarted` will produce a better result?

**Comment by bricker** [comment]
I'll try out your suggestions and see which one performs best.
