### ISSUE TITLE
Need Invisibilia avatar

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#53]
@sdillingham if you can send this to me I'll add it in, thanks!

**Comment by sdillingham** [comment]
xxhdpi size attached.
![program_avatar_invisibilia](https://cloud.githubusercontent.com/assets/442483/7150049/4eccc2f2-e2ca-11e4-9848-3744c37d4fb6.png)

**Comment by sdillingham** [comment]
xhdpi size attached.
![program_avatar_invisibilia](https://cloud.githubusercontent.com/assets/442483/7150054/58b2c8f2-e2ca-11e4-817f-799d2eb157f8.png)

**Comment by sdillingham** [comment]
hdpi size attached.
![program_avatar_invisibilia](https://cloud.githubusercontent.com/assets/442483/7150057/628d8254-e2ca-11e4-9aef-705aa33d4554.png)

**Comment by sdillingham** [comment]
mdpi size attached.
![program_avatar_invisibilia](https://cloud.githubusercontent.com/assets/442483/7150060/6af5eb98-e2ca-11e4-9778-5b592a6b6b53.png)

**Comment by bricker** [comment]
Thanks!
