### ISSUE TITLE
FEATURE: Live Rewind

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#61]
Originally not implemented because of poor support for the functionality in Android.

**Comment by ewr** [comment]
These are notes that I had originally written up for implementing rewind on the web, but I'll post them here in case you want to go down one of the non-HLS routes for Android.

----

# Goal
Implement rewind functionality for the SCPR website, allowing listeners to start from the beginning of a program like they can via the KPCC iPhone app.

# Implementation Options
## HLS
On the iPhone app, we use Apple's HTTP Live Streaming to provide a multi-hour playlist that the client can provide navigation within. Apple's HLS implementation in AVPlayer provides a `seekToDate` function that can be used to seek to a certain time, and a `seekToTime` function for seeking forward and backward. It handles the segment selection underneath.

There is limited HLS support in web browsers right now (Safari on OS X). There are some javascript / flash options for supporting HLS in the browser, but it is unclear whether they support seeking or seeking by date.

## Stream with start time
One simple implementation option would be to simply connect to the regular stream endpoint while passing a `timestamp` option as a parameter. This will start a normal stream play from that point in the rewind buffer.

Seeking once the stream is playing would need to be accomplished by stopping that stream and creating a new one with the appropriate seeked `timestamp`.

## Socket Sidechannel
Early on in StreamMachine's development, I had done an example connection type that used a simple stream with a websocket sidechannel for seek communication. This prevented the need to tear down the existing connection and set up a new one on each seek.

The code no longer exists inside StreamMachine, but a similar strategy would not be difficult to add.

----

The stream with start time would be a simple win. Right now it looks like `?timestamp` only takes unix timestamps, but I would want to add support for iso8601 date string parsing. We would also want to think through the best way to communicate what time we're actually returning, the extents of the buffer options, etc.

HLS is still preferred (short-lived connections are the future), but I'm glad to work with you on supporting one of these other options if it's helpful.

**Comment by bricker** [comment]
Thanks for this! Honestly, due to the original timeframe for this project and the agreement that Live Rewind could come later, I had taken yours and Sean's word for it (that HLS support on Android was limited) and not really investigated the options. 

The timestamp option would be easy for me to implement and we could get something out the door in a matter of weeks. If SM already supports it, I can add this quickly.

Doing a quick google search, it seems that most of the problems with HLS on Android are related to video playback, so maybe we could make it work for us. This would take me a little bit longer though as I'm not familiar with the HLS spec. 

I'll make Live Rewind my top priority for the next release. I'll try implementing HLS proper first, and if it turns out to be problematic then I'll use the timestamp. I'll keep you updated with progress and any questions that come up.

**Comment by sdillingham** [comment]
@bricker - here are the icon assets you'll need for the Live Rewind feature (RW30, FF30, and "Start of Show"):

[live-rewind-assets.zip | uploaded via ZenHub](https://files.zenhub.io/55d76537191da5cc1b9065c5)
