### ISSUE TITLE
High priority: Paused audio will start playing after audio focus is "given back"

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#62]
I haven't verified this but I think this is a bug:

1. Start an episode stream.
2. Pause the episode.
3. Receive a notification that causes a sound (eg. text message) or a call
4. After the notification sound is finished or the call is ended, the episode will start playing automatically.

When losing audio focus, we should set a flag indicating whether the audio was actually playing when AF was lost. When AF is given back, the audio should only be started if the flag is set.

**Comment by bricker** [comment]
This would happen for Preroll too. It doesn't happen for Livestream because LS can't be technically "paused", it's either playing or it's released.

**Comment by bricker** [comment]
Another idea is to maybe remove audio focus entirely when the player is paused, and take it back when played. This would fix this problem and is probably a more correct solution. This would also prevent the audio player from being destroyed if an episode is paused and then some other music is streaming.

**Comment by sdillingham** [comment]
I agree with your last comment Bryan - losing focus whenever on-demand/preroll audio is paused seems to me to be the correct behavior.

**Comment by bricker** [comment]
Although I think the second solution is a technically better one, since we're nearing a final release I decided to implement the simpler solution to avoid doing too big of a refactor of the audio focus handlers and risk breaking something that's already been tested thoroughly. This won't affect the user experience negatively.
