### ISSUE TITLE
FEATURE: Sleep Timer

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#70]
Reinstitute a sleep timer feature to allow users to set a timer that will automatically turn off the live stream at a specified time. Users can set a sleep timer duration anywhere between 5mins and 8 hours in 5 minute increments. The current iPhone app can be used as a functional reference for how the feature is designed and implemented.

## User Stories

- [x] Add Sleep/Alarm item to Top Level Menu 
- [x] In the Sleep Timer view, users can select the number of hours and minutes for their timer, then press start and begin playing the live stream
- [x] When the sleep timer is engaged, a “sleep” icon appears on the Live Live screen that allows users to cancel their current timer
- [x] When the current sleep timer has expired, the live stream stops playing and goes into a paused state
- [x] App has Mixpanel events for Sleep Timer features 

Mixpanel Events to add:

* menuSelectionSleep/Wake
* userSetSleepTimer (when sleep timer is armed)
* SleepTimerEnded (when sleep timer turns stream off)
* SleepTimerCanceled (when user manually cancels sleep timer)

Link to download design specs: https://www.dropbox.com/s/dsoarq92e1vjfac/SleepTimerDesignSpecs.zip?dl=0

**Comment by sdillingham** [comment]
There are a few icon assets that will be needed to support the sleep/wake features. When you create a branch and start work on this, I can commit the icon assets you'll need.

**Comment by bricker** [comment]
Okay, cool. I think I'll start on this next week.

**Comment by bricker** [comment]
This is mostly finished I just need to style the counter on the Live Stream page and add the ability to cancel by clicking on the counter on the Live page.

**Comment by bricker** [comment]
This is complete except for the icons needed.

**Comment by sdillingham** [comment]
Hey @bricker - I've zipped up and included the assets you'll need (at all sizes) and shared them here:

https://www.dropbox.com/s/78a28es4lxy2q47/sleep-wake-assets.zip?dl=0

There's one asset to use in the Menu, and two other icons to use for the Sleep Timer and Alarm Clock buttons. The sleep timer icon can also be used on the player screen when the countdown timer is engaged.

**Comment by bricker** [comment]
Thanks! I'll throw these in tonight and push a new build into alpha.
