### ISSUE TITLE
Missing a few assets

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#78]
From the linter:

* Missing the following drawables in 'drawable-xxhdpi': menu_microphone.png (found in drawable-mdpi, drawable-hdpi)
* Missing the following drawables in 'drawable-xhdpi': menu_microphone.png (found in drawable-mdpi, drawable-hdpi)
* Missing the following drawables in 'drawable-xxxhdpi': ic_audio_btn_pause_normal.png, ic_audio_btn_play_normal.png, ic_audio_btn_stop_normal.png, ic_check.png, ic_chevron_right.png... (47 more)

I added the xxxhdpi folder for the stopwatch and clock assets, but none of the other assets have xxxhdpi sizes.

**Comment by sdillingham** [comment]
Hey Bryan,

This _should_ be all of the xxxhdpi assets for the app - please let me know if there are others that are still missing:

https://www.dropbox.com/s/jgzie2lxmzj26a2/drawable-xxxhdpi.zip?dl=0

And here are the two sizes of the menu_microphone.png that you're missing:

https://www.dropbox.com/s/4462nmdhw68elxo/menu-microphone.zip?dl=0

**Comment by bricker** [comment]
Thanks! I'll get these in for the 3.2.0 release next month.

**Comment by bricker** [comment]
This is included in v76
