### ISSUE TITLE
Update ad serving endpoint

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#80]
KPCC is discontinuing its use of Triton for ad serving on 6/30 and will be switching to a new ad server, AdTech, starting 7/1. @ewr has been able to replicate the VAST response that Triton returns in the current ad calls we make, so to switch over to AdTech all that should need to be done is to update this:

https://github.com/SCPR/KPCC-Android/blob/6648596f0a10438829e9cef6948d9eb110156986/app/src/main/java/org/kpcc/android/PrerollManager.java#L24

to use this endpoint instead:

http://adserver.adtechus.com/?adrawdata/3.0/5511.1/3590533/0/0/header=yes;cookie=no;adct=text/xml;guid=%s:%s

**Comment by bricker** [comment]
Thanks Sean, I will get to this early this week.

**Comment by sdillingham** [comment]
Thanks Bryan. If for any reason you won't be able to get this change ready to test by Tuesday afternoon so we can promote to production early Wednesday morning, just give me a heads up.

**Comment by ewr** [comment]
The wrong URL got used for this update. We should be using the URL above... The one that got implemented is the iPhone placement.

**Comment by bricker** [comment]
@ewr The URL in Sean's post is missing when I look at it, it's probably adblock hiding it, I grabbed the URL from the iphone source. I updated to the correct URL and pushed a new version to beta. I don't have my phone with me right now to test.
