### ISSUE TITLE
Add Twitter Fabric (Crashlytics + Answers)

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#81]
To get better realtime visibility into app crashes and top-line metrics, we're adding Twitter's new Fabric SDK (https://get.fabric.io/android) into our apps and would like to include Android. Fabric's SDK wraps several "kits" with different functionality; we're interested in the Crashlytics kit.

@bricker I'll send you a direct invite to our Fabric account. Once you have that, getting the SDK installed and running should be straightforward. A couple of relevant docs here:

https://dev.twitter.com/fabric/android/integrating
http://docs.fabric.io/android/crashlytics/introduction.html

Let me know if you have any questions!

**Comment by bricker** [comment]
This is included in v76
