### ISSUE TITLE
Live Rewind: "Back to Live" button appears even when playhead is at "live"

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#85]
STR:

1. Start a new session and play the live stream.
2. Press pause.
3. The "back to live" button appears immediately.

I think what we want is a behavior where the playhead needs to be > 2mins behind live before the state of the button changes from "Rewind to Start" to "Back to Live".

**Comment by bricker** [comment]
Fixed in 3.2.0
