### ISSUE TITLE
Live Rewind: Add progress spinner and sound when user engaged the "Rewind to Start" and "Back to live" seeking functions 

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#88]
Rewind audio file attached here:
[rewind_beat.mp3 | uploaded via ZenHub](https://files.zenhub.io/560c3f1dd7a4f68e2d4f11a3)

Using the current progress spinner in the Android app is fine (it doesn't need to match what we're doing on iOS), but the getting the timing is important - the transition should  last ~3secs to allow the audio sample to complete before playing the live stream.

**Comment by bricker** [comment]
Fixed in 3.2.0
