### ISSUE TITLE
REPORT: Wrong show playing

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#96]
Not sure if the rewind caused this glitch but when I tried listening to Airtalk, when it was streaming, Morning Edition kept playing.

**Comment by bricker** [comment]
Another comment: It started up with Air Talk when it’s supposed to be Marketplace. I hit rewind-back-to-beginning-of-the-show and Marketplace came on. It seems fine now.

**Comment by vsinghkpcc** [comment]
@bricker So far here's my best pass at STR around what these reports are experiencing.

1. Play the live stream in the app.
2. Pause the live stream and note the current program airing.
3. Background the app.
4. Open the app after a new program is scheduled to start. (The UI will display "Up Next: [the show that is scheduled to air]")
5. Hit the play button
6. Hear that the live stream plays from where the user left off, but the UI is referencing the current show scheduled to be on air 

NOTES: 
- I was within the rewind buffer when testing
- At step 6 I was unable to use the scrubber
- At step 6, after used the "rewind 30" button the UI would update correctly and interacting with UI was as expected

**Comment by vsinghkpcc** [comment]
Testing some other issues, when playing the live stream from a cold open, the UI will display the show that's scheduled to air, but what I'm hearing is from much earlier. (ex. I hit play the live stream for "BBC News Hour" but the audio I heard was from Take Two)

**Comment by bricker** [comment]
Fixed in v83 — this was caused by a race condition in which the stream would start playing before the metadata was fully loaded and so it was playing the beginning of the HLS window.
