### ISSUE TITLE
App crashes when browsing internet

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#97]
Sometimes the application stops working if I browse the Internet while listening to a prerecorded program like my favorite show, Snap.

**Comment by vsinghkpcc** [comment]
At this point I can't find exact STR for this, but I did notice the audio from the KPCC App would stutter as pages took a long time loaded in the Chrome App. 

Sometimes the KPCC App audio stopped completely (seemingly always related to a page in Chrome taking a long time to load, but I couldn't get that to happen consistently).

**Comment by bricker** [comment]
I can't repro this one, it may just be a low memory case where Chrome is hogging the memory and KPCC (which also uses a significant amount of memory) is killed by the OS.

**Comment by bricker** [comment]
I'm going to close this until we get more reports.
