### ISSUE TITLE
REPORT: Incorrect program showing on live screen

### ISSUE THREAD

**Issue by bricker** [SCPR/KPCC-Android#99]
It seems like once a day on average when I open the app and go to listen live, the program shown is accurate but the audio I am hearing is something else, like marketplace should be on, the screen says marketplace, but I'm hearing air talk for example. sometimes [go to beginning of show] fixes it, sometimes I have to do the change program and come back trick I mentioned above.

**Comment by vsinghkpcc** [comment]
Closing in favor of #96
